nguage: generic
services:
  - docker
env:
  matrix:
    - DOCKER_TAG='liangxin1300/haleap:15.1'
      PACKAGES='crmsh pacemaker corosync python3 iproute2 which iputils vim tar bzip2'
    - DOCKER_TAG='liangxin1300/haleap:42.3'
      PACKAGES='crmsh pacemaker corosync iproute2 which iputils vim tar bzip2 hostname'
before_install:
  - docker pull "${DOCKER_TAG}"
script:
  - docker run -d --name=hanode1 --hostname hanode1 --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro ${DOCKER_TAG}
  - docker exec -t hanode1 /bin/sh -c "zypper -n install ${PACKAGES}"
  - docker exec -t hanode1 /bin/sh -c "crm cluster init -y"
  - docker exec -t hanode1 /bin/sh -c "crm_mon -1"
