language: generic
services:
  - docker
stages:
  - test
jobs:
  include:
    - stage: test
      before_install:
        - docker pull liangxin1300/haleap:15.1
        - docker pull liangxin1300/haleap:42.3
      script:
        - docker run -d --name=hanode1 --hostname hanode1 --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro liangxin1300/haleap:15.1
        - docker exec -t hanode1 /bin/sh -c "zypper -n install crmsh pacemaker corosync python3 iproute2 which iputils vim tar bzip2"
        - docker exec -t hanode1 /bin/sh -c "crm cluster init -y"
        - docker exec -t hanode1 /bin/sh -c "crm_mon -1"
        - docker run -d --name=hanode2 --hostname hanode2 --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro liangxin1300/haleap:42.3
        - docker exec -t hanode1 /bin/sh -c "zypper -n install crmsh pacemaker corosync"
        - docker exec -t hanode1 /bin/sh -c "crm cluster init -y"
        - docker exec -t hanode1 /bin/sh -c "crm_mon -1"
